name: verify

on:
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false
      - run: |
          terraform -chdir=terraform init -input=false
          terraform -chdir=terraform plan -input=false -no-color > plan.txt
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: plan
          path: plan.txt

  comment:
    needs: plan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pull-requests: write
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: plan
      - run: |
          gh release download v4.14.19 --repo suzuki-shunsuke/tfcmt --pattern 'tfcmt_linux_amd64.tar.gz'
          gh attestation verify tfcmt_linux_amd64.tar.gz \
            --repo suzuki-shunsuke/tfcmt \
            --signer-repo suzuki-shunsuke/go-release-workflow
          tar -xzf tfcmt_linux_amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./tfcmt plan --disable-label --patch -- cat plan.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./tfcmt --var 'target:example' plan --disable-label --patch -- cat plan.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
